// <auto-generated/>

using System;

namespace GameCloud.UCenter.Common.Dumper
{
    [AttributeUsage(AttributeTargets.All)]
    public class DumperToAttribute : Attribute
    {
        public DumperToAttribute(string value)
        {
            this.Value = value;
        }

        public string Value { get; private set; }
    }
}